# Generated by Django 5.2.4 on 2025-08-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
