# Generated by Django 5.2.4 on 2025-08-18 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='verified',
            new_name='verified_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
    ]
