# Generated by Django 5.2.4 on 2025-08-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_company_address_companyaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='verification_documant',
        ),
        migrations.AddField(
            model_name='company',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='company/verification_document/'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='permissions',
            field=models.JSONField(default={'product': {'create': False, 'delete': False, 'read': True, 'update': False}, 'product_category': {'create': False, 'delete': False, 'read': False, 'update': False}, 'user': {'create': False, 'delete': False, 'read': True, 'update': False}}),
        ),
    ]
